### ISSUE TITLE
Restart server each time I make changes to HTML page

### ISSUE THREAD

**Issue by DREWDL** [middleman/middleman-blog#294]
Love Middleman but each time I make a change to my html files, I need to quit and then rerun middleman server.

I get this issue when I run the server.
Unresolved specs during Gem::Specification.reset: minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

I assume this shouldn't be happening. Thanks!

**Comment by tdreyno** [comment]
What kind of environment are you using? OS? Vagrant? Docker?

This definitely isn't happening for anyone else.

Why did you file this bug under `middleman-blog`?

**Comment by DREWLEPP** [comment]
I apologize. I guess I didn't realize where I submitted this. I found the page
when googling for the answer. I'm working on a mac. Not sure out how I can find
out that additional info.





On Sun, May 8, 2016 5:42 PM, Thomas Reynolds notifications@github.com wrote:
What kind of environment are you using? OS? Vagrant? Docker?

This definitely isn't happening for anyone else.

Why did you file this bug under middleman-blog ?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub



Drew Lepp User Experience/Product Designer

Portfolio: drewlepp.com Blog: drewlepp.com/blog



Social: @ drewlepp LinkedIn Instagram

**Comment by tdreyno** [comment]
Hi Drew, so, the stuff I mentioned are very complicated tools certain types of developers setup so a group of devs can work with exact same environment. It sounds like you probably setup this project yourself, so those are unlikely to be in use. Let me know if someone else setup your environment.

Can you post the `Gemfile.lock` file in your project folder?

**Comment by iwarner** [comment]
Closing as stagnant
