### ISSUE TITLE
Missing parent in site herarchy while using tags

### ISSUE THREAD

**Issue by Jeeppler** [middleman/middleman-blog#303]
The middleman-blog extension sets the parent element to nil, if the article is categoriezed by tag. 

E. g. 
recipes -> tag -> lunch -> 03_20_noodles_tomato //03_20_noodles_tomato does not have a parent (expected parent recipes)

recipes -> 03_20_noodles_tomato //the parent is set correctly to recipes

This actually breaks the following extension: https://github.com/marnen/middleman-breadcrumbs

For more details see: https://github.com/marnen/middleman-breadcrumbs/issues/7

**Comment by iwarner** [comment]
This is probably because the Tag page is a proxy template

Can you provide some feature tests for this?

I actually wrote the same issue in breadcrumbs : https://github.com/marnen/middleman-breadcrumbs/issues/15

And wrote my own referenced in that link.

**Comment by Jeeppler** [comment]
> This is probably because the Tag page is a proxy template.

Yes, most likely. 

> Can you provide some feature tests for this?

I do not understand the question. What would you like me to test?

**Comment by vinc** [comment]
I don't really know if it's related but I'm using `middleman-breadcrumbs` and I couldn't get the breadcrumb working on tag pages because tags are missing a parent in site hierarchy.

If fixed this quite simply by creating a `tags.html.erb` page in my `blog` directory. Now tag pages like `/blog/tags/foo.html` have a parent that is `/blog/tags.html` and the breadcrumb works.

I'm leaving this information here in case someone have the same problem.

See this issue that may be related: https://github.com/marnen/middleman-breadcrumbs/issues/15

**Comment by Jeeppler** [comment]
@vinc Yes, this issue is related to it. Interesting that you only had to create a `tags.html.erb` file.
